workflows:
  ios-kmp-workflow:
    name: AccuDose KMP iOS App
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Xcode select
        script: |
          xcode-select -s /Applications/Xcode.app
      - name: Build iOS App
        script: |
          cd app/iosApp
          xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO
    artifacts:
      - app/iosApp/build/Release-iphoneos/*.ipa
      
